# TCL File Generated by Component Editor 23.1
# Wed Oct 16 20:13:18 MDT 2024
# DO NOT MODIFY


# 
# led_patterns_avalon "led_patterns_avalon" v1.0
#  2024.10.16.20:13:18
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module led_patterns_avalon
# 
set_module_property DESCRIPTION ""
set_module_property NAME led_patterns_avalon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME led_patterns_avalon
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL led_patterns_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file led_patterns_avalon.vhd VHDL PATH led_patterns_avalon.vhd TOP_LEVEL_FILE
add_fileset_file led_pattern_generator.vhd VHDL PATH ../../hdl/led-patterns/led_pattern_generator.vhd
add_fileset_file led_pattern_fsm.vhd VHDL PATH ../../hdl/led-patterns/led_pattern_fsm.vhd
add_fileset_file led_patterns.vhd VHDL PATH ../../hdl/led-patterns/led_patterns.vhd
add_fileset_file async_conditioner.vhd VHDL PATH ../../hdl/async-conditioner/async_conditioner.vhd
add_fileset_file debouncer.vhd VHDL PATH ../../hdl/async-conditioner/debouncer.vhd
add_fileset_file one_pulse.vhd VHDL PATH ../../hdl/async-conditioner/one_pulse.vhd
add_fileset_file synchronizer.vhd VHDL PATH ../../hdl/synchronizer/synchronizer.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock_sink_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset_sink_reset reset Input 1


# 
# connection point export
# 
add_interface export conduit end
set_interface_property export associatedClock clock_sink
set_interface_property export associatedReset ""
set_interface_property export ENABLED true
set_interface_property export EXPORT_OF ""
set_interface_property export PORT_NAME_MAP ""
set_interface_property export CMSIS_SVD_VARIABLES ""
set_interface_property export SVD_ADDRESS_GROUP ""

add_interface_port export push_button push_button Input 1
add_interface_port export switches switches Input 4
add_interface_port export led led Output 8

